{% set name = "xnatutils" %}
{% set version = "0.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xnatutils-{{ version }}.tar.gz
  sha256: 0058b43f1890d7a3fc2bb2fdd232840a560e3decde01a910f5e02ed81c952f13

build:
  number: 1
  noarch: python
  entry_points:
    - xnat-ls = xnatutils.ls_:cmd
    - xnat-get = xnatutils.get_:cmd
    - xnat-put = xnatutils.put_:cmd
    - xnat-rename = xnatutils.rename_:cmd
    - xnat-varget = xnatutils.varget_:cmd
    - xnat-varput = xnatutils.varput_:cmd
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - xnat >=0.6
    - progressbar2 >=3.16.0
    - future >=0.16

test:
  commands:
    - pip list
    - pip check
    - xnat-ls --version
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://australian-imaging-service.github.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Xnat-utils is a collection of scripts for conveniently up/downloading and listing data on/from XNAT based on the XnatPy package'
  description: |
    This is a xnat cli to interact with xnat server
    return a list of projects, subjects or sessions.
  dev_url: https://github.com/Australian-Imaging-Service/xnatutils
  doc_url: https://australian-imaging-service.github.io/user_docs/
  doc_source_url: https://australian-imaging-service.github.io/docs/

extra:
  recipe-maintainers:
    - mthang
